### ISSUE TITLE
同一页面上使用多个进度条会有性能问题

### ISSUE THREAD

**Issue by shunia** [jcyuan/FairyGUI-PixiJS#15]
实际项目里使用了8个短进度条,里面的图片使用平铺实现拉伸.
项目fps设置为60帧.
显示进度条fps范围大概是15-25帧.
隐藏进度条fps是满的.

**Comment by jcyuan** [comment]
investigating

**Comment by jcyuan** [comment]
tested but couldn't be reproduced, please provide some demo.

**Comment by jcyuan** [comment]
close as poster does not respond in time
