### ISSUE TITLE
GTextInput 控件输入时报错

### ISSUE THREAD

**Issue by onlycxue** [jcyuan/FairyGUI-PixiJS#16]
在编辑器中把text文本设置为输入，不勾选单行(勾选了单行不会报错)，把fui 文件加载到程序中运行
并点击input控件进行输入  会报如下错误
![ad574a6f-407a-4a7d-b110-f4303d1cd211](https://user-images.githubusercontent.com/4102400/33412149-97ff437e-d5c4-11e7-9212-1980c1314508.png)

**Comment by jcyuan** [comment]
fixed
