### ISSUE TITLE
GObject.getGear在使用了颜色控制时会运行时报错

### ISSUE THREAD

**Issue by shunia** [jcyuan/FairyGUI-PixiJS#2]
错误重现:
1. 在编辑器里,为按钮组件增加`属性控制`,选择`颜色控制`.
2. 保存.
3. 发布定义.
4. 代码中创建该按钮组件.
5. 出现报错`Uncaught ... 'setup' ...`, 空对象上没有setup方法.

问题出在GObject.getGear:
```typescript
case GearType.Color:
    if (fgui.isColorGear(this))
        gear = new GearColor(this);
```

这个case失败了的话,gear就是`null`,这样就会导致下面的`setupAfterAdd`报错:
```typescript
this.getGear(index).setup(cxml);
```

谷主的`GObject.getGear`方法是没有会导致null的逻辑的:
```typescript
case 4:
    gear = new GearColor(this);
```

**Comment by jcyuan** [comment]
this is a legacy problem caused by the old UI editor, gearColor for button is not supported. but anyway I will add more detailed error info to throw.
