### ISSUE TITLE
v1.3.0 版本 清除含有GList 组件的界面的时候会有报错

### ISSUE THREAD

**Issue by onlycxue** [jcyuan/FairyGUI-PixiJS#25]
报错如下：
![2018-07-09 4 03 41](https://user-images.githubusercontent.com/4102400/42438115-b157a5b6-8391-11e8-89ea-3aac96bf75bc.png)

**Comment by jcyuan** [comment]
investigating

**Comment by jcyuan** [comment]
tested but it seems no such error? please provide an example, thanks.

**Comment by jcyuan** [comment]
reopen it if you provide test demo, thanks.

**Comment by onlycxue** [comment]
The demo url. 
https://github.com/onlycxue/FairyGUI-list-crash.git 

The list overflow option must be hidden. 

![2018-07-28 6 59 07](https://user-images.githubusercontent.com/4102400/43355901-5e12f8fe-9298-11e8-90cc-ecdd0c145bd1.png)

**Comment by jcyuan** [comment]
bug fixed, thank you very much.
