### ISSUE TITLE
GButton as GList item may cause "ItemClick" event fires more than once

### ISSUE THREAD

**Issue by shunia** [jcyuan/FairyGUI-PixiJS#26]
Simple use case:
```
let list;

list.itemRenderer = (index, object) => {
    // any logic
};
list.numItems = 4;
list.numItems = 5;
list.numItems = 6;

list.on(fgui.ListEvent.ItemClick, onClick, this);

let onClick = () => {
    console.log('GList item clicked');  // will output multiple times as the times of calling GList.numItems
};
```

This problem appears to be related to `PIXI`'s default event emitter, it won't check for duplicate event handlers, thus when `GList` renders, the default behavier `child.click(this.$clickItem, this)` will trigger multiple times, and when the event is fired, `this.$clickItem` will be triggered multiple times too.

But if the `remove` logic works right, this won't happen. However...
```
public removeChildToPoolAt(index: number): void {
     let child: GObject = super.removeChildAt(index);
     this.returnToPool(child);
}
```
This **super** call will bypass the remove event logic.

Please fix this ASAP!

**Comment by jcyuan** [comment]
fixed in dev branch, will merge asap.
