### ISSUE TITLE
原本的namespace fairygui不应该使用fgui,导致编辑器导出的代码会报错

### ISSUE THREAD

**Issue by shunia** [jcyuan/FairyGUI-PixiJS#3]
导出的代码默认使用的fairygui进行引用,修改成fgui之后,导出的代码全部报错.

**Comment by jcyuan** [comment]
I'll change the exporting strategy, let's say to export templates according to which SDK you use but not language.

**Comment by jcyuan** [comment]
fixed, please wait for the new Editor release.
