### ISSUE TITLE
使用controller改变selectedIndex时，如果改变的包括GTextInput，则GTextInput在下次出现的时候无法点击

### ISSUE THREAD

**Issue by OrpineJelly** [jcyuan/FairyGUI-PixiJS#30]

**Comment by OrpineJelly** [comment]
当GTextInput被移除时触发的destory方法，移除了监听，重新加上去的时候没有把监听加回来
`InputDelegate.prototype.destroy = function () {
                if (!this.$inited)
                    return;
                this.$input.$removeFromStage();
                this.$textField.off(fgui.InteractiveEvents.Down, this.textFieldDownHandler, this);
                fgui.GRoot.inst.off(fgui.InteractiveEvents.Down, this.onStageDown, this);
                this.$input.off("updateText", this.updateText, this);
                this.$input.off("__focusChanged" /* CHANGED */, this.focusHandler, this);
                this.$inited = false;
            };`

**Comment by jcyuan** [comment]
@OrpineJelly 可以提供一个简单的DEMO吗？谢谢。

**Comment by jcyuan** [comment]
改变selectedIndex时对input的操作是怎样的？只有显示和隐藏吗？

**Comment by OrpineJelly** [comment]
> 改变selectedIndex时对input的操作是怎样的？只有显示和隐藏吗？

就是一个状态显示input一个状态隐藏input，如果把input放在一个组件里，把这个组件再放到controller里，不会有问题，但直接显示隐藏input就不行
在隐藏input的时候，输入事件被移除了，而显示input的时候输入事件没被加回来

**Comment by jcyuan** [comment]
了解了，这边查一下。谢谢。

**Comment by jcyuan** [comment]
fixed 73b7609
