### ISSUE TITLE
最近发现list滚动的时候，没有快速滚动效果

### ISSUE THREAD

**Issue by zkybeijing** [jcyuan/FairyGUI-PixiJS#31]
最近发现list滚动的时候，没有快速滚动效果

**Comment by zkybeijing** [comment]
发现 const deltaTime: number = Math.max(now - this.$lastMoveTime, 1 / frameRate);
now - this.$lastMoveTime  时间变长了，导致快速滚动的时候，移动距离变小
自己做测试的时候也发现两次收到move事件的时候，时间间隔变长，我们现在处理方法是改成
 const deltaTime: number = 1 / frameRate；这样看起来问题消失，就是不知道有没有从根本上解决的方法

**Comment by zkybeijing** [comment]
一进入游戏的时候是正常的，打了一场战斗回来就变了，开始时候两次move的时间是大概是 1/60，打了一场战斗回来发现 时间大概是开始的5倍多，开始怀疑是不是游戏掉帧了，导致时间变长，后来打印fps，fps并没有变，最初是在手机上发现的，以为手机比较卡，后来在电脑上也一样，电脑上都是满帧的，现在确定是两次move时间的间隔变长了，具体为啥变长不清楚

**Comment by jcyuan** [comment]
@zkybeijing 可以提供一个简单的demo吗。比较难重现

**Comment by jcyuan** [comment]
https://github.com/jcyuan/FairyGUI-PixiJS/releases/tag/1.3.2

reopen if use this release to test but the problem still exists, thanks.   @zkybeijing
