### ISSUE TITLE
在缩放后文本可见区域有问题

### ISSUE THREAD

**Issue by 958877748** [jcyuan/FairyGUI-PixiJS#33]
在 PIXI.Application参数-渲染比例resolution=2 时  
等于1时就没问题

**Comment by 958877748** [comment]
导致文本只能显示左上角那4分之1

**Comment by 958877748** [comment]
截图上传不上来

**Comment by 958877748** [comment]
<img width="114" alt="1" src="https://user-images.githubusercontent.com/31437616/46728604-c28d7f00-ccb5-11e8-8a93-1af1a02a52d9.PNG">
<img width="141" alt="11" src="https://user-images.githubusercontent.com/31437616/46728611-c91bf680-ccb5-11e8-9b2f-6821a5fb5260.PNG">

**Comment by jcyuan** [comment]
@958877748  这个暂时不会被支持，因为fgui默认一直都是全屏大小的，所以内部元素都是自适应的（使用`scaleMode: fgui.StageScaleMode.FIXED_WIDTH`, `orientation: fgui.StageOrientation.LANDSCAPE`等适应选项）
所以需要关闭application的resolution。

**Comment by jcyuan** [comment]
但后期有可能会支持（默认切除界面如果超出的话）
