### ISSUE TITLE
动画链接放到Safari浏览器打开中，点击热区被挤下来，画面上的功能按钮点击无反应

### ISSUE THREAD

**Issue by mubai09** [jcyuan/FairyGUI-PixiJS#35]
1、苹果手机未设置竖向锁定
2、复制链接到手机内置浏览器中打开阅读故事
3、打开链接页面
结果：页面上的按钮，点击没有反应，进步追查后发现是：点击热区整体下移了

![default](https://user-images.githubusercontent.com/44629679/47788764-9cf01480-dd4d-11e8-8bb1-5cc6772d23f6.png)

**Comment by jcyuan** [comment]
can you please provide some info like what is your browser, OS?

and can you try 'stage.updateScreenSize()' and check if the problem still exists?

**Comment by jcyuan** [comment]
please be noticed that the safari patch is removed from the UIStage.ts in the commit 33862f1. there is actually no resize event triggers when the safari tool bar shows up, so you have to find a way to handle that event and call `.stage.updateScreenSize()` at that time.

safari的toolbar出现后不会触发resize事件，所以无法重新计算点击映射坐标，需要你自己找到resize的触发时机然后调用`.stage.updateScreenSize();`。谢谢。

@mubai09
