### ISSUE TITLE
能不能将pixi原生对象放入fairygui 容器里面？

### ISSUE THREAD

**Issue by loohoo** [jcyuan/FairyGUI-PixiJS#36]
fairygui是不是只能作为hud使用， 不能将pixi显示对象放入任何fairygui容器内部？ 
@jcyuan

**Comment by jcyuan** [comment]
it does.

`
    let myObj = new PIXI.Graphics();
    ....
    (fgui.GRoot.inst.getChildByName("test") as fgui.GGraph).setNativeObject(myObj);
`

create an `empty` graph in the editor, and call `setNativeObjuect` to insert any native object into it.

but don't forget to remove/destory your own object while destroying the fgui object it was related to.
