### ISSUE TITLE
编辑器里,如果对高级组使用了关联,组中的文字会丢失对齐效果

### ISSUE THREAD

**Issue by shunia** [jcyuan/FairyGUI-PixiJS#5]
复现步骤:
1. 创建一个文本组件,自动大小设置为`无`
2. 文本组件设置对齐为`左右居中`,`上下居中`
3. 用组把文本组件包起来,设置成高级组
4. 高级组设置关联,对象`容器组件`,`左右居中`,`上下居中`

现象:
文本组件的对齐效果全部丢失

PS:
1. 未测试高级组的关联对象不是`容器组件`是否会引起这个问题
2. 未测试高级组的其他关联类型是否会引起这个问题
3. 未测试其他组件是否受影响(比如有一个大容器,里面包了一个居中关联的子组件)

**Comment by jcyuan** [comment]
this is the basic knowledge of the editor, you don't have chance to set relation for the top most container in the editor, you have to set it in code `com.addRelation(parentEle, ...)` which means you can only set relations for it's children but not itself.
